// Code generated by "stringer -type=FileChange"; DO NOT EDIT

package file

import "fmt"

const _FileChange_name = "CreatedModifiedDeleted"

var _FileChange_index = [...]uint8{0, 7, 15, 22}

func (i FileChange) String() string {
	if i < 0 || i >= FileChange(len(_FileChange_index)-1) {
		return fmt.Sprintf("FileChange(%d)", i)
	}
	return _FileChange_name[_FileChange_index[i]:_FileChange_index[i+1]]
}
