// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package database

import "fmt"

const _Operator_name = "EQ"

var _Operator_index = [...]uint8{0, 2}

func (i Operator) String() string {
	if i < 0 || i >= Operator(len(_Operator_index)-1) {
		return fmt.Sprintf("Operator(%d)", i)
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
